### ISSUE TITLE
 The new embedding does not support the old FlutterView.

### ISSUE THREAD

**Issue by vaidehee** [AppsFlyerSDK/flutter_appsflyer_sdk#19]
i have created a project and when i try to run it, it gives me this error
can anybody help me solve this as i need it urgently?
thanks in advance

`2020-03-11 13:03:34.968 5235-5235/com.example.flutter_appflyer E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.flutter_appflyer, PID: 5235
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.flutter_appflyer/com.example.flutter_appflyer.MainActivity}: java.lang.UnsupportedOperationException: The new embedding does not support the old FlutterView.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.UnsupportedOperationException: The new embedding does not support the old FlutterView.
        at io.flutter.embedding.engine.plugins.shim.ShimRegistrar.view(ShimRegistrar.java:82)
        at com.appsflyer.appsflyersdk.AppsflyerSdkPlugin.<init>(AppsflyerSdkPlugin.java:58)
        at com.appsflyer.appsflyersdk.AppsflyerSdkPlugin.registerWith(AppsflyerSdkPlugin.java:69)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:17)
        at com.example.flutter_appflyer.MainActivity.configureFlutterEngine(MainActivity.kt:10)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:185)
        at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:418)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by ShaharAF** [comment]
Hi @vaidehee. Thank you for openinig this issue. 
We've just released a new version for this plugin. 
Can you check if it solves the problem?

**Comment by vaidehee** [comment]
> Hi @vaidehee. Thank you for openinig this issue.
> We've just released a new version for this plugin.
> Can you check if it solves the problem?

Hello,
thank you for looking into this issue,
i checked with new version and it works like a charm!! :) thanks again
