### ISSUE TITLE
v^1.2.2 iOS initSdk(...) returns error ```type 'String' is not a subtype of type 'Map<dynamic, dynamic>'```

### ISSUE THREAD

**Issue by vagrantrobbie** [AppsFlyerSDK/flutter_appsflyer_sdk#21]
**Describe the bug**
I have updated to the latest version of `appsflyer_sdk` from 1.2.1 to 1.2.2 and now receive the error  
 ```
type 'String' is not a subtype of type 'Map<dynamic, dynamic>'
```  

in my app as well as the example app
  
  
I have attached my `flutter doctor` for extra reference:
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-NZ)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
[✓] VS Code (version 1.38.1)
[✓] Connected device (2 available)

• No issues found!
```

After running `pod install`
```
Downloading dependencies
Using AppsFlyerFramework (5.1.0)
Using Flutter (1.0.0)
Using appsflyer_sdk (1.1.3)
Generating Pods project
Integrating client project
```

### EDIT:  

I should probably add a code sample of where this is happening  

```
_appsFlyerSdk = AppsflyerSdk(AppsFlyerOptions(
        afDevKey: appsFlyerSDKDevKey,
        appId: appsFlyerAppId,
        showDebug: doDebug
    ));   
try {
      await _appsFlyerSdk.initSdk(true, true);
      return null;
    } catch(error) {
     /* HERE ------ > */ print("error = $error");
      return null;
    }
```  

> error = type 'String' is not a subtype of type 'Map<dynamic, dynamic>'

**Comment by vagrantrobbie** [comment]
though it does seem to log successfully according to the XCode debug  

```
<~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~~+~>
<~+~   SEND Track-App-Launch:   https://launches.appsflyer.com/api/v4.9/iosevent?app_id=[myappid]&buildnumber=5.1.0
<~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~~+~>
```

**Comment by ShaharAF** [comment]
Thanks for opening this issue @vagrantrobbie. I will investigate this

**Comment by egorikem** [comment]
Same here

**Comment by strokine** [comment]
Same here:
```
[INFO]  AppsFlyer: Launch
[DEBUG] AppsFlyer: ASIdentifierManager loaded
[DEBUG] AppsFlyer: ADClient loaded
[DEBUG] AppsFlyer: CTTelephonyNetworkInfo loaded
[DEBUG] AppsFlyer: FBSDKAppEventsUtility not found
[VERBOSE-2:shell.cc(199)] Dart Error: Unhandled exception:
type 'String' is not a subtype of type 'Map<dynamic, dynamic>'
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:13)
<asynchronous suspension>
#1      AppsflyerSdk.initSdk (package:appsflyer_sdk/src/appsflyer_sdk.dart:159:27)
#2      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
#3      AppsflyerSdk.initSdk (package:appsflyer_sdk/src/appsflyer_sdk.dart:141:22)
#4      BabaApp._initTracking (package:gr_pro/main.dart:76:46)
#5      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
#6      BabaApp._initTracking (package:gr_pro/main.dart:65:23)
#7      BabaApp.build (package:gr_pro/main.dart:41:5)
#8      StatelessElement.build (package:flutter/src/widgets/framework.dart:4291:28)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
#10     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#11     BuildOwner.bu<…>
```

**Comment by rodion-m** [comment]
The same on version 1.2.2:
```
_TypeError
type '_OneByteString' is not a subtype of type 'Map<dynamic, dynamic>'
platform_channel.dart in MethodChannel.invokeMethod at line 321
Called from: <asynchronous suspension>
appsflyer_sdk.dart in AppsflyerSdk.initSdk at line 159
Globals.dart in Globals.init at line 128
Called from: <asynchronous suspension>
main.dart in main at line 19
Called from: async_patch.dart in _AsyncAwaitCompleter.start
main.dart in main at line 17
Called from: hooks.dart in _runMainZoned.<fn>.<fn>
```
Please fix it.

**Comment by vagrantrobbie** [comment]
@rodion-m is this error related to iOS `initSdk(...)`?

**Comment by rodion-m** [comment]
> @rodion-m is this error related to iOS `initSdk(...)`?

Sorry, do you mean how I call initSdk? Like this: `appsFlyerSdk.initSdk(null, null);`

**Comment by vagrantrobbie** [comment]
yep. Is this error thrown when calling initSdk on iOS? I don't get this so just double checking we are looking at the same bug

**Comment by rodion-m** [comment]
> yep. Is this error thrown when calling initSdk on iOS? I don't get this so just double checking we are looking at the same bug

Oh sorry, yes! It's iOS 13.1.3 - **release** build.

**Comment by ShaharAF** [comment]
I've merged @rostopira fix, thanks for the help 👍
